services:
  postgres:
    image: postgres:16
    container_name: postgres_service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: pnpm run dev --host