services:
  postgres:
    image: postgres:16
    container_name: madlen_postgres_service
    ports:
      - "4034:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./assets/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - postgres_network

  frontend:
    build:
      context: ./client
    container_name: madlen_frontend_service
    ports:
      - "3050:3000"
    environment:
      - VITE_BASE_URL=http://localhost:3051
    volumes:
      - ./client:/app

  backend:
    build:
      context: ./server
    container_name: madlen_backend_service
    ports:
      - "3051:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:4034/postgres

networks:
  postgres_network:
    driver: bridge