services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: pnpm run dev --host