services:
  postgres:
    image: postgres:16
    container_name: postgres_service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./assets/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  frontend:
    build:
      context: ./client
    container_name: frontend_service
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: pnpm run dev --host

  backend:
    build:
      context: ./server
    container_name: backend_service
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres